### ISSUE TITLE
pip install nvidia-pyindex is not working

### ISSUE THREAD

**Issue by rexdivakar** [NVIDIA/tensorflow#10]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by DEKHTIARJonathan** [comment]
Please add more context. It is virtually impossible to help you here.

**Comment by mstorer3772** [comment]
I'm have a similar/identical problem.  Windows 10, installing from an Anaconda3 (python3.8.8) cmd.exe window.  I get the following output.  

```
(base) d:\tools\Anaconda3>pip install nvidia-pyindex
Collecting nvidia-pyindex
  Downloading nvidia-pyindex-1.0.8.tar.gz (6.4 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Tools\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_eb4d05add1984c6a9ecb02d94dfaecaa\\setup.py'"'"'; __file__='"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_eb4d05add1984c6a9ecb02d94dfaecaa\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mstor\AppData\Local\Temp\pip-pip-egg-info-tkf8trx1'
         cwd: C:\Users\mstor\AppData\Local\Temp\pip-install-q9xyn12l\nvidia-pyindex_eb4d05add1984c6a9ecb02d94dfaecaa\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mstor\AppData\Local\Temp\pip-install-q9xyn12l\nvidia-pyindex_eb4d05add1984c6a9ecb02d94dfaecaa\setup.py", line 214, in <module>
        raise OSError("Your operating system is not supported by "
    OSError: Your operating system is not supported by `nvidia-pyindex`: win32.
    Only Linux systems are supported.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d8/bc/24a480fb81539c1c067b8866f2e5fccb26831b216cee7a1349caaaa3e825/nvidia-pyindex-1.0.8.tar.gz#sha256=154db873fcb36c1645be6c99b643ded1e4909e59213cb51b7f5eb104a120dbce (from https://pypi.org/simple/nvidia-pyindex/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading nvidia-pyindex-1.0.6.tar.gz (6.7 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Tools\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_01f6ec1b315e43369b73c17bdeff7947\\setup.py'"'"'; __file__='"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_01f6ec1b315e43369b73c17bdeff7947\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mstor\AppData\Local\Temp\pip-pip-egg-info-vk3umft9'
         cwd: C:\Users\mstor\AppData\Local\Temp\pip-install-q9xyn12l\nvidia-pyindex_01f6ec1b315e43369b73c17bdeff7947\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mstor\AppData\Local\Temp\pip-install-q9xyn12l\nvidia-pyindex_01f6ec1b315e43369b73c17bdeff7947\setup.py", line 214, in <module>
        raise OSError("Your operating system is not supported by "
    OSError: Your operating system is not supported by `nvidia-pyindex`: win32.
    Only Linux systems are supported.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/e6/56a6909f95409a31865399282f5f5a1692e89e7f5f5c5e7633d201e0fbd0/nvidia-pyindex-1.0.6.tar.gz#sha256=4b025aef886cb134cc3935c3b3eeaf32585b135f4752511aabf1f3f6e4606ac8 (from https://pypi.org/simple/nvidia-pyindex/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading nvidia-pyindex-1.0.5.tar.gz (6.1 kB)
Building wheels for collected packages: nvidia-pyindex
  Building wheel for nvidia-pyindex (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Tools\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_1ed4cff53f1b47978981128beac19b1c\\setup.py'"'"'; __file__='"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_1ed4cff53f1b47978981128beac19b1c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\mstor\AppData\Local\Temp\pip-wheel-whygsq4n'
       cwd: C:\Users\mstor\AppData\Local\Temp\pip-install-q9xyn12l\nvidia-pyindex_1ed4cff53f1b47978981128beac19b1c\
  Complete output (25 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\nvidia_pyindex
  copying nvidia_pyindex\cmdline.py -> build\lib\nvidia_pyindex
  copying nvidia_pyindex\utils.py -> build\lib\nvidia_pyindex
  copying nvidia_pyindex\__init__.py -> build\lib\nvidia_pyindex
  running egg_info
  writing nvidia_pyindex.egg-info\PKG-INFO
  writing dependency_links to nvidia_pyindex.egg-info\dependency_links.txt
  writing entry points to nvidia_pyindex.egg-info\entry_points.txt
  writing top-level names to nvidia_pyindex.egg-info\top_level.txt
  reading manifest file 'nvidia_pyindex.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'nvidia_pyindex.egg-info\SOURCES.txt'
  installing to build\bdist.win-amd64\wheel
  running install
  '"nvidia_pyindex uninstall"' is not recognized as an internal or external command,
  operable program or batch file.
  error: [WinError 2] The system cannot find the file specified
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  COMMAND: InstallCommand
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  ----------------------------------------
  ERROR: Failed building wheel for nvidia-pyindex
  Running setup.py clean for nvidia-pyindex
Failed to build nvidia-pyindex
Installing collected packages: nvidia-pyindex
    Running setup.py install for nvidia-pyindex ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\Tools\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_1ed4cff53f1b47978981128beac19b1c\\setup.py'"'"'; __file__='"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_1ed4cff53f1b47978981128beac19b1c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mstor\AppData\Local\Temp\pip-record-4kcd92ak\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Tools\Anaconda3\Include\nvidia-pyindex'
         cwd: C:\Users\mstor\AppData\Local\Temp\pip-install-q9xyn12l\nvidia-pyindex_1ed4cff53f1b47978981128beac19b1c\
    Complete output (7 lines):
    running install
    '"nvidia_pyindex uninstall"' is not recognized as an internal or external command,
    operable program or batch file.
    error: [WinError 2] The system cannot find the file specified
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    COMMAND: InstallCommand
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Tools\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_1ed4cff53f1b47978981128beac19b1c\\setup.py'"'"'; __file__='"'"'C:\\Users\\mstor\\AppData\\Local\\Temp\\pip-install-q9xyn12l\\nvidia-pyindex_1ed4cff53f1b47978981128beac19b1c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mstor\AppData\Local\Temp\pip-record-4kcd92ak\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Tools\Anaconda3\Include\nvidia-pyindex' Check the logs for full command output.

```

**Comment by rexdivakar** [comment]
Hey @mstorer3772  were u able to try build it from source ? cox even that failed for me

**Comment by DEKHTIARJonathan** [comment]
@mstorer3772 this error is quite explicit.

OSError: Your operating system is not supported by `nvidia-pyindex`: win32.
Only Linux systems are supported.

We don't support windows platform only linux systems (specifically Ubuntu 20.04 is guaranteed support)
