### ISSUE TITLE
UT //tensorflow/python:saver_test failed

### ISSUE THREAD

**Issue by candyzone** [NVIDIA/tensorflow#25]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):N
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.15
- Python version:python3.6
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):gcc7.5.0
- CUDA/cuDNN version:-
- GPU model and memory:-

**Describe the current behavior**

bazel test --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0  --copt="-march=native" //tensorflow/python:saver_test
FAILED

Traceback (most recent call last):
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/training/saver_test.py", line 2419, in testClearDevicesOnExport
    10, size=[1, 10])
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1165, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 474, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 266, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 375, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 375, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 276, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/admin/chen.ding/gitlab/code/tensorflow_2021/bazel-bin/tensorflow/python/saver_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 315, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'new_model/optimize' cannot be interpreted as a Tensor. ("The name 'new_model/optimize' refers to an Operation not in the graph.")

**Describe the expected behavior**

UT pass 

**root casse**
https://github.com/NVIDIA/tensorflow/blob/r1.15.5%2Bnv21.05/tensorflow/python/training/optimizer.py#L659
It changes NoOp name here(suffix with '-apply') , but without change in 'saver_test‘ test case

**Comment by candyzone** [comment]
Why NV change NoOp name with suffix “-apply“ in TensorFlow source code? Any other reason?
