### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement nvidia-tensorflow[horovod] (from versions: 0.0.1.dev4, 0.0.1.dev5) ERROR: No matching distribution found for nvidia-tensorflow[horovod]

### ISSUE THREAD

**Issue by riariam** [NVIDIA/tensorflow#87]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 20.04
- Python version:3.6.13
- Installed using virtualenv? pip? conda?:pip
- CUDA/cuDNN version:11.4
- GPU model and memory:RTX 3090

**Describe the problem**
I encountered an error running the command 'pip install --user nvidia-tensorflow[horovod]'
I have updated pip and installed python = 3.6. I also installed nvidia-pyindex 1.0.1 first, but I still have this error(I have tried py3.8 and it didn't work either)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
 pip install nvidia-pyindex 
      Successfully built nvidia-pyindex
      Installing collected packages: nvidia-pyindex
      Successfully installed nvidia-pyindex-1.0.1

**Comment by nluehr** [comment]
I've seen similar errors fixed by updating pip as follows:
```
python3 -mpip install --upgrade pip
```

**Comment by andynugent** [comment]
I've seeing the same issue running Python 3.8.10 (amd64) and pip 24.3.1

python.exe -m pip install nvidia-pyindex

> Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
> Requirement already satisfied: nvidia-pyindex in c:\users\andyn\appdata\local\programs\python\python38\lib\site-packages (1.0.9)


python.exe -m pip install nvidia-tensorflow[horovod] 

> 
> Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
> Collecting nvidia-tensorflow[horovod]
>   Downloading nvidia-tensorflow-0.0.1.dev5.tar.gz (7.9 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [30 lines of output]
>       Traceback (most recent call last):
>         File "C:\Users\andyn\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "C:\Users\andyn\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "C:\Users\andyn\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "C:\Users\andyn\AppData\Local\Temp\pip-build-env-ehwf2_6v\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>         File "C:\Users\andyn\AppData\Local\Temp\pip-build-env-ehwf2_6v\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\andyn\AppData\Local\Temp\pip-build-env-ehwf2_6v\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "C:\Users\andyn\AppData\Local\Temp\pip-build-env-ehwf2_6v\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
>           exec(code, locals())
>         File "<string>", line 150, in <module>
>       RuntimeError:
>       ###########################################################################################
>       The package you are trying to install is only a placeholder project on PyPI.org repository.
>       This package is hosted on NVIDIA Python Package Index.
> 
>       This package can be installed as:
>       ```
>       $ pip install nvidia-pyindex
>       $ pip install nvidia-tensorflow
>       ```
> 
>       Please refer to NVIDIA instructions: https://github.com/NVIDIA/tensorflow#install.
>       ###########################################################################################
> 
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
>
