### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by ZhangShiyue** [NVIDIA/tensorflow#99]
**System information**
- OS Platform and Distribution: macOS ventura13.5
- TensorFlow version: none
- Python version: 3.11.4
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the problem**
Hey, I was unable to install nvidia-pyindex. Please refer to the log below. Could you please help me with this? Thanks!

**Any other info / logs**
```
    szhang1061@L1J6FP26KD ~ % pip install nvidia-pyindex -i https://pypi.python.org/simple 
    Looking in indexes: https://pypi.python.org/simple
    Collecting nvidia-pyindex
      Using cached nvidia-pyindex-1.0.9.tar.gz (10 kB)
      Installing build dependencies ... done
      Getting requirements to build wheel ... done
      Installing backend dependencies ... done
      Preparing metadata (pyproject.toml) ... done
    Building wheels for collected packages: nvidia-pyindex
      Building wheel for nvidia-pyindex (pyproject.toml) ... error
      error: subprocess-exited-with-error
      
    × Building wheel for nvidia-pyindex (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [85 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib
        creating build/lib/nvidia_pyindex
        copying nvidia_pyindex/cmdline.py -> build/lib/nvidia_pyindex
        copying nvidia_pyindex/__init__.py -> build/lib/nvidia_pyindex
        copying nvidia_pyindex/utils.py -> build/lib/nvidia_pyindex
        running egg_info
        writing nvidia_pyindex.egg-info/PKG-INFO
        writing dependency_links to nvidia_pyindex.egg-info/dependency_links.txt
        writing entry points to nvidia_pyindex.egg-info/entry_points.txt
        writing top-level names to nvidia_pyindex.egg-info/top_level.txt
        reading manifest file 'nvidia_pyindex.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        adding license file 'LICENSE.md'
        writing manifest file 'nvidia_pyindex.egg-info/SOURCES.txt'
        installing to build/bdist.macosx-10.9-universal2/wheel
        running install
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        COMMAND: InstallCommand
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        Traceback (most recent call last):
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-install-kb7cn8ab/nvidia-pyindex_ca43951a3b0f4f0e81315e3bea4ed344/nvidia_pyindex/utils.py", line 20, in get_configuration_files
            output = subprocess.check_output(command, stderr=subprocess.STDOUT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
            raise CalledProcessError(retcode, process.args,
        subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11', '-c', 'from pip._internal.configuration import get_configuration_files; print(get_configuration_files())']' returned non-zero exit status 1.
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
            return _build_backend().build_wheel(wheel_directory, config_settings,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel
            return self._build_with_temp_dir(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
            self.run_setup()
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
            super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
            exec(code, locals())
          File "<string>", line 238, in <module>
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
                   ^^^^^^^^^^^^^^^^^^
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
            super().run_command(command)
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 399, in run
            self.run_command("install")
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
            super().run_command(command)
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-build-env-nify1voq/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "<string>", line 172, in run
          File "<string>", line 71, in _install_nvidia_pypi_index
          File "/private/var/folders/zs/t0cyppjd3wx9jvspzndwyzpw0000gq/T/pip-install-kb7cn8ab/nvidia-pyindex_ca43951a3b0f4f0e81315e3bea4ed344/nvidia_pyindex/utils.py", line 24, in get_configuration_files
            raise RuntimeError(output) from e
        RuntimeError: Traceback (most recent call last):
          File "<string>", line 1, in <module>
        ModuleNotFoundError: No module named 'pip'
        
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for nvidia-pyindex
  Failed to build nvidia-pyindex
  ERROR: Could not build wheels for nvidia-pyindex, which is required to install pyproject.toml-based projects
```

**Comment by fisch1123** [comment]
请问这个问题解决了嘛，我也是遇到这个问题，一直找不到解决的办法

**Comment by z-x-x136** [comment]
请问这个问题解决了嘛，我也是遇到这个问题，一直找不到解决的办法

**Comment by sbhavani** [comment]
@ZhangShiyue which TF version are you trying to install? You can also include the extra index url like this: 
`pip install nvidia-tensorflow[horovod] --extra-index-url=https://pypi.ngc.nvidia.com/`
